### PR TITLE
Made kick me command more restrictive

### PR DESCRIPTION
**Pull request by SkyBirdSoar**
No longer triggers on "xxxx do not kick me blah blah"

### CODE REVIEW

**Comment by LizzyTrickster** [comment]
But where is your sacrifice?

**Comment by SkyBirdSoar** [comment]
Angels do not demand sacrifices.

**Comment by LizzyTrickster** [comment]
This one does

**Comment by SkyBirdSoar** [comment]
I have compromised on my stand to remove the command in its entirety.

**Comment by vifino** [comment]
no.

**Pull request closed without merging**
